# Generated by Django 4.0.4 on 2022-08-18 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('point_b', models.URLField(max_length=512)),
                ('visited', models.BooleanField(default=False)),
                ('content', models.TextField(default='', null=True)),
                ('taken', models.BooleanField(default=False, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('point_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Point_A', to='razorback.link')),
            ],
            options={
                'unique_together': {('point_a', 'point_b')},
            },
        ),
    ]
