# Generated by Django 3.2.8 on 2021-10-29 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('point_b', models.URLField()),
                ('visited', models.BooleanField(default=False)),
                ('point_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Point_A', to='razorback.url')),
            ],
        ),
    ]
