# Generated by Django 3.1.2 on 2021-11-01 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('razorback', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='URL',
            new_name='Link',
        ),
    ]
