# Generated by Django 3.2.8 on 2021-11-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razorback', '0003_alter_link_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='point_b',
            field=models.URLField(max_length=512),
        ),
    ]
