# Generated by Django 3.2.8 on 2021-11-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razorback', '0004_alter_link_point_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
