# Generated by Django 3.2.8 on 2021-11-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razorback', '0005_link_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='content',
            field=models.TextField(default='', null=True),
        ),
    ]
